policy_holder_name = "Akash Kumar"
policy_number = "21201"
product_name = "InsureBot"
policy_start_date = "21 march 2025"
total_premium_paid = "0"
premium_due_date = "21 March 2025"
sum_assured = "100"
fund_value = "one lakh"