ALL_RESPONSE = [
    {
        "question" : "Hello and very Good Morning Sir, May I speak with {policy_holder_name}?",
        "response": {
            "yes": [
                    "Yes",
                    "Yes, speaking",
                    "Speaking",
                    "This is him",
                    "This is her",
                    "I am {policy_holder_name}",
                    "You are speaking to him",
                    "You are speaking to her",
                    "Yes, go ahead",
                    "Yes, tell me",
                    "Yes, who's this?",
                    "Yes, who’s calling?",
                    "Yes, what is it regarding?",
                    "Yes, what do you want to talk about?",
                    "Yes, how can I help you?",
                    "Yes, this is {policy_holder_name}",
                    "Yes, I am available",
                    "Yes, I’m listening",
                    "Yes, please continue",
                    "Yes, speaking with {policy_holder_name}",
                    "Yes, I’m the policyholder",
                    "Yes, this is he",
                    "Yes, this is she",
                    "Yes, Veena ji",
                    "Yes, bolo",
                    "Boliye",
                    "Haan",
                    "Haan ji",
                    "Haan boliye",
                    "Haan, main bol raha hoon",
                    "Haan, main bol rahi hoon",
                    "Haan, main hi hoon",
                    "Haan, kaun bol raha hai?",
                    "Haan, kya baat hai?",
                    "Main {policy_holder_name} bol raha hoon",
                    "Main {policy_holder_name} bol rahi hoon",
                    "Main bol raha hoon",
                    "Main bol rahi hoon",
                    "Main hoon",
                    "Ji, main hoon",
                    "Ji haan",
                    "Ji, kya baat hai?",
                    "Ji, kaun bol raha hai?",
                    "Hello, haan boliye",
                    "Hello, main bol raha hoon",
                    "Hello, main bol rahi hoon",
                    "Yes, who are you?",
                    "Yes, I’m here",
                    "Yes, I’m on the line",
                    "Yes, you can talk to me"
                ],
            "He/she is busy or can’t talk right now": [
                    "He is busy right now",
                    "She is busy right now",
                    "He can't talk right now",
                    "She can't talk right now",
                    "He is not available",
                    "She is not available",
                    "He is in a meeting",
                    "She is in a meeting",
                    "He is sleeping",
                    "She is sleeping",
                    "He is not home",
                    "She is not home",
                    "He is out",
                    "She is out",
                    "He is at work",
                    "She is at work",
                    "He is driving",
                    "She is driving",
                    "He is bathing",
                    "She is bathing",
                    "He is busy, call later",
                    "She is busy, call later",
                    "He will call you back",
                    "She will call you back",
                    "He is on another call",
                    "She is on another call",
                    "He is not feeling well",
                    "She is not feeling well",
                    "He is not here",
                    "She is not here",
                    "He stepped out",
                    "She stepped out",
                    "He is not reachable",
                    "She is not reachable",
                    "He is in the washroom",
                    "She is in the washroom",
                    "He is praying",
                    "She is praying",
                    "He is talking to someone else",
                    "She is talking to someone else",
                    "He will be back in a while",
                    "She will be back in a while",
                    "He is having lunch",
                    "She is having lunch",
                    "He is not available to talk",
                    "She is not available to talk",
                    "Not a good time to talk",
                    "Please call later",
                    "He is not in a position to talk",
                    "She is not in a position to talk",
                    "He can’t come to the phone right now",
                    "She can’t come to the phone right now"
                ],
            "no": [
                    "No",
                    "No, he is not available",
                    "No, she is not available",
                    "No, he doesn't live here",
                    "No, she doesn't live here",
                    "No, wrong number",
                    "No, I think you have the wrong number",
                    "No, {policy_holder_name} is not here",
                    "No, I am not {policy_holder_name}",
                    "No, this is not {policy_holder_name}",
                    "No, you can't speak to him",
                    "No, you can't speak to her",
                    "No, he won't talk to you",
                    "No, she won't talk to you",
                    "No, he is not interested",
                    "No, she is not interested",
                    "No, not the right person",
                    "No, he doesn’t use this number",
                    "No, she doesn’t use this number",
                    "No, I don’t know him",
                    "No, I don’t know her",
                    "No, you have dialed the wrong number",
                    "No, you’re mistaken",
                    "Wrong number",
                    "This is not the right number",
                    "This is not {policy_holder_name}'s number",
                    "He doesn’t stay here anymore",
                    "She doesn’t stay here anymore",
                    "He has shifted",
                    "She has shifted",
                    "Sorry, no",
                    "Sorry, can’t help",
                    "Sorry, you’ve got the wrong person",
                    "No idea who you're talking about"
                ]
        }
    },
    {
        "question": "My name is Veena and I am an Executive calling on behalf of ValuEnable Life Insurance Co. Ltd, this is a service call with regards to your life insurance policy. Is this the right time to speak to you regarding the renewal of your policy?",
        "response": {
            "Not a good time to talk now": [
                    "Not a good time right now",
                    "I’m busy at the moment",
                    "I’m in a meeting",
                    "Can you call later?",
                    "I’m driving right now",
                    "I’ll call you back",
                    "Please call later",
                    "Not now, I’m occupied",
                    "I can’t talk right now",
                    "I’m at work",
                    "I’m with someone right now",
                    "I’m in the middle of something",
                    "Can we talk later?",
                    "This isn’t a good time",
                    "I’m not free now",
                    "I’ll talk later",
                    "Busy right now, please call back",
                    "Please call after some time",
                    "I’m outside",
                    "I’m not at home",
                    "I’m in the market",
                    "Can’t talk, in a function",
                    "Can you please call tomorrow?",
                    "I'm getting ready to leave",
                    "Call me in the evening",
                    "I’m attending a call already",
                    "I’m not in a position to talk",
                    "I’m having lunch",
                    "I’m taking rest",
                    "I'm not feeling well",
                    "Very busy now, sorry"
                ],
            "yes": [
                    "Yes",
                    "Yes, this is the right time",
                    "Yes, go ahead",
                    "Yes, please continue",
                    "Yes, tell me",
                    "Yes, I’m listening",
                    "Yes, I have time",
                    "Yes, I can talk now",
                    "Yes, what is it about?",
                    "Yes, you can talk now",
                    "Yes, I’m free",
                    "Yes, I’m available",
                    "Yes, you may continue",
                    "Sure, go ahead",
                    "Sure, I can talk",
                    "Sure, please tell me",
                    "Sure, I’m listening",
                    "Tell me",
                    "Boliye",
                    "Haan boliye",
                    "Haan, bataiye",
                    "Haan, boliye kya baat hai?",
                    "Ji, boliye",
                    "Ji haan",
                    "Ji, kya baat hai?",
                    "Ji, main sun raha hoon",
                    "Ji, main sun rahi hoon",
                    "Yes, I’m here",
                    "Yes, I was expecting your call",
                    "Yes, please go ahead",
                    "Yes, I have a few minutes",
                    "Yes, what do I need to do?"
                ],
            "He/she is busy or can’t talk right now": [
                    "He is busy right now",
                    "She is busy right now",
                    "He can't talk at the moment",
                    "She can't talk at the moment",
                    "He is not available right now",
                    "She is not available right now",
                    "He is in a meeting",
                    "She is in a meeting",
                    "He is resting right now",
                    "She is resting right now",
                    "He is driving",
                    "She is driving",
                    "He is not home right now",
                    "She is not home right now",
                    "He is occupied at the moment",
                    "She is occupied at the moment",
                    "He is on another call",
                    "She is on another call",
                    "He is taking a bath",
                    "She is taking a bath",
                    "He is praying right now",
                    "She is praying right now",
                    "He is attending a function",
                    "She is attending a function",
                    "He is not in a position to talk",
                    "She is not in a position to talk",
                    "He asked not to be disturbed",
                    "She asked not to be disturbed",
                    "He will call you back later",
                    "She will call you back later",
                    "Now is not a good time for him",
                    "Now is not a good time for her",
                    "Please call later, he’s busy",
                    "Please call later, she’s busy",
                    "He is sleeping",
                    "She is sleeping",
                    "He stepped out",
                    "She stepped out"
                ]
        }
    },
    {
        "question": "It will take just 2 minutes of your time. Can we discuss it right now or should I reschedule your call at a better time?",
        "response": {
            "yes": [
                    "Yes",
                    "Yes, we can talk now",
                    "Yes, please go ahead",
                    "Yes, you can continue",
                    "Yes, sure",
                    "Yes, I have 2 minutes",
                    "Yes, no problem",
                    "Yes, talk to me",
                    "Yes, tell me",
                    "Sure, we can talk now",
                    "Sure, go ahead",
                    "Sure, I’m listening",
                    "Sure, you can talk",
                    "I’m free, please continue",
                    "Yes, what is it about?",
                    "Yes, I’m available now",
                    "Yes, I can spare 2 minutes",
                    "Yes, I’m here",
                    "Yes, continue",
                    "Go ahead",
                    "Boliye",
                    "Haan boliye",
                    "Haan, baat kijiye",
                    "Haan, bataiye",
                    "Haan ji",
                    "Ji haan, boliye",
                    "Ji, bataiye",
                    "Ji, baat kijiye",
                    "Abhi baat kar sakte hain",
                    "Haan, abhi baat ho sakti hai",
                    "Theek hai, boliye",
                    "Theek hai, bataiye",
                    "Yes, please tell me quickly",
                    "Yes, let’s do it now",
                    "Yes, I’m ready",
                    "Yes, now is fine"
                ],
            "not a good time to talk now": [
                    "Not right now, please",
                    "I’m busy at the moment",
                    "This is not a good time",
                    "Can you call me later?",
                    "Please call me after some time",
                    "I’m in a meeting",
                    "I’m driving right now",
                    "I’ll call you back",
                    "Call me later",
                    "Now is not a good time",
                    "I can’t talk right now",
                    "I’m occupied",
                    "I’m not free at the moment",
                    "I’m outside",
                    "I’m at work",
                    "I’m resting right now",
                    "I’m with someone, call later",
                    "Please reschedule the call",
                    "Let’s talk some other time",
                    "Not possible to talk now",
                    "Can we talk later?",
                    "I’m not in a position to talk",
                    "I’m attending a function",
                    "I’m having lunch",
                    "I’m not available right now",
                    "Sorry, I’m busy",
                    "Sorry, not now",
                    "Sorry, later please",
                    "I’m about to leave",
                    "Very busy right now, call later",
                    "I’ll be free in the evening",
                    "I’m not feeling well, call later"
                ],
        }
    },
    {
        "question": "May I know your relationship with {policy_holder_name}? ",
        "response": {
            "Define Relationship with Customer": [
                    "I am his brother",
                    "I am her brother",
                    "I am his sister",
                    "I am her sister",
                    "I am his son",
                    "I am her son",
                    "I am his daughter",
                    "I am her daughter",
                    "I am his father",
                    "I am her father",
                    "I am his mother",
                    "I am her mother",
                    "I am his husband",
                    "I am her husband",
                    "I am his wife",
                    "I am her wife",
                    "I am his friend",
                    "I am her friend",
                    "I am his cousin",
                    "I am her cousin",
                    "I am his uncle",
                    "I am her uncle",
                    "I am his aunt",
                    "I am her aunt",
                    "I am his nephew",
                    "I am her nephew",
                    "I am his niece",
                    "I am her niece",
                    "I am his grandfather",
                    "I am her grandfather",
                    "I am his grandmother",
                    "I am her grandmother",
                    "I am his son-in-law",
                    "I am her son-in-law",
                    "I am his daughter-in-law",
                    "I am her daughter-in-law",
                    "I am his brother-in-law",
                    "I am her brother-in-law",
                    "I am his sister-in-law",
                    "I am her sister-in-law",
                    "I am related to him",
                    "I am a relative",
                    "I’m a family member",
                    "We are family",
                    "He is my father",
                    "She is my mother",
                    "He is my brother",
                    "She is my sister",
                    "He is my husband",
                    "She is my wife",
                    "He is my uncle",
                    "She is my aunt",
                    "He is my friend",
                    "She is my friend",
                    "She is my cousin",
                    "He is my cousin",
                    "I’m his neighbor",
                    "I’m her neighbor"
                ]
        }
    },
    {
        "question": "Do you handle {policy_holder_name}'s life insurance policy number {policy_number}? Are you aware of the details of this policy?",
        "response": {
            "yes": [
                    "Yes",
                    "Yes, I do",
                    "Yes, I handle it",
                    "Yes, I manage the policy",
                    "Yes, I take care of it",
                    "Yes, I look after it",
                    "Yes, I am aware of the policy",
                    "Yes, I know the details",
                    "Yes, I am familiar with the policy",
                    "Yes, I’ve seen the documents",
                    "Yes, I know about the policy",
                    "Yes, I take care of such matters",
                    "Yes, it’s under my supervision",
                    "Yes, I have access to the policy",
                    "Yes, I’ve gone through it",
                    "Yes, I am responsible for it",
                    "Yes, I take care of his/her policies",
                    "Yes, I’m the one handling it",
                    "Yes, I’m aware of this policy",
                    "Yes, I know about policy number {policy_number}",
                    "Yes, I’ve seen that policy",
                    "Yes, I know everything about it",
                    "Yes, I help with that",
                    "Yes, I’ve managed it before",
                    "Yes, I deal with his/her insurance matters",
                    "Yes, he/she asked me to take care of it",
                    "Yes, I handle these things for him/her",
                    "Yes, I take care of such documents"
                ],
            "no":  [
                    "No",
                    "No, I don’t handle it",
                    "No, I’m not responsible for it",
                    "No, I don’t manage the policy",
                    "No, I’m not aware of the details",
                    "No, I don’t know about it",
                    "No, I have no information on this policy",
                    "No, I’m not familiar with it",
                    "No, someone else handles it",
                    "No, I’m not involved",
                    "No, I don’t take care of that",
                    "No, I’m not authorized to talk about it",
                    "No, I don’t have access to the policy",
                    "No, I’ve never seen the documents",
                    "No, I’m not the right person",
                    "No, I can’t help with this",
                    "No, please talk to the policyholder",
                    "No, I’m not the one handling it",
                    "No, I don’t deal with insurance matters",
                    "No, I’m unaware of this policy",
                    "No, that’s not my responsibility",
                    "No, you have the wrong person",
                    "No, I’m not involved with the policy",
                    "No, I don’t know anything about it"
                ]
        }
    },
    {
        "question": "Let me start by confirming your policy details. Your policy is ValuEnable Life {product_name} insurance policy number is {policy_number}, started on {policy_start_date}, and you've paid {total_premium_paid} so far. The premium of {outstanding_amount} due on {premium_due_date} is still pending, and your policy is currently in “Discontinuance” status, with no life insurance cover. Could you please let me know why you haven’t been able to pay the premium? ",
        "response": {
            "If Customer Explain Reason":  [
                    "I forgot to pay the premium",
                    "I was not aware of the due date",
                    "I am facing financial difficulties right now",
                    "I lost my job recently",
                    "I am going through some personal issues",
                    "I was out of town and couldn't pay",
                    "I didn’t receive the payment reminder",
                    "The amount was higher than I expected",
                    "I am waiting for my salary",
                    "I had some medical emergencies",
                    "I had other urgent expenses",
                    "I was not sure how to make the payment",
                    "I had technical issues while paying",
                    "I thought the payment was auto-debited",
                    "I needed some more time to arrange the funds",
                    "I was confused about the policy status",
                    "I was not informed properly",
                    "I have been busy and forgot",
                    "I am planning to pay soon",
                    "I wanted to discuss options before paying",
                    "I am considering discontinuing the policy",
                    "I did not receive any notice about the discontinuance",
                    "I didn’t realize the policy was in discontinuance status",
                    "I wasn’t expecting this much outstanding amount",
                    "I had a dispute with the agent",
                    "I didn’t find the premium affordable",
                    "I am waiting for some financial help",
                    "I was not able to access online payment",
                    "I am not in a position to pay at the moment",
                    "I had some banking issues",
                    "I’m sorry for the delay",
                    "I’ll arrange the payment as soon as possible"
                ],
            "agree to pay": [
                    "Yes, I will pay soon",
                    "I will arrange the payment shortly",
                    "I will clear the pending premium as soon as possible",
                    "I’m planning to pay the premium",
                    "I will make the payment today",
                    "I will pay by the due date",
                    "I will transfer the amount soon",
                    "I’ll pay the outstanding premium",
                    "I will take care of it immediately",
                    "I’ll pay as soon as I can",
                    "I’ll settle the amount shortly",
                    "I will make the payment now",
                    "I’ll clear the dues soon",
                    "I’m arranging the funds to pay",
                    "I’ll complete the payment soon",
                    "I promise to pay soon",
                    "I’m working on the payment",
                    "I’ll pay it without delay",
                    "You can expect the payment shortly",
                    "I’m committed to paying",
                    "I will pay the premium for sure",
                    "I’m on it",
                    "I’m ready to pay",
                    "I’m processing the payment",
                    "I’ll make the payment ASAP",
                    "I will take care of the payment",
                    "I’ll ensure payment is done soon"
                ],
            "already paid": [
                    "I have already paid the premium",
                    "The payment has been made",
                    "I paid the premium recently",
                    "The premium was paid last week",
                    "I completed the payment yesterday",
                    "The outstanding amount has been cleared",
                    "I have settled the premium",
                    "Payment is done",
                    "I transferred the amount already",
                    "I have made the payment",
                    "The premium is already paid",
                    "It’s already paid",
                    "Payment was processed",
                    "I paid online",
                    "The bank transaction is complete",
                    "I have proof of payment",
                    "The payment was successful",
                    "I have cleared the dues",
                    "The payment was done on time",
                    "The premium is fully paid",
                    "I have paid before the due date",
                    "I took care of the payment",
                    "I have submitted the payment",
                    "Payment confirmation received",
                    "The premium has been paid",
                    "I already cleared the balance"
                ],
            "don't have policy band" :  [
                    "I don’t have the policy bond",
                    "I don’t have the policy document",
                    "I lost the policy papers",
                    "I haven’t received the policy bond yet",
                    "I don’t know where the policy bond is",
                    "The policy document is missing",
                    "I can’t find the policy bond",
                    "I never got the policy papers",
                    "I don’t have any documents related to the policy",
                    "The policy bond was misplaced",
                    "I haven’t received any policy documents",
                    "I don’t have a copy of the policy",
                    "The policy bond was never given to me",
                    "I lost the original policy bond",
                    "I’m not aware of the policy bond",
                    "I have no paperwork for the policy",
                    "I didn’t get the policy bond in the mail",
                    "I don’t have any proof of the policy",
                    "I can’t produce the policy documents",
                    "I haven’t seen the policy bond"
                ],
            "can't pay": [
                    "I can’t pay right now",
                    "I’m unable to pay at the moment",
                    "I don’t have the money currently",
                    "I’m facing financial difficulties",
                    "I lost my job recently",
                    "I have other urgent expenses",
                    "I’m going through some tough times",
                    "I can’t arrange the funds right now",
                    "I’m waiting for my salary",
                    "I have some medical bills to pay",
                    "I’m not in a position to pay",
                    "I’m having financial problems",
                    "I can’t afford the premium now",
                    "I’m struggling to manage expenses",
                    "I need more time to pay",
                    "I’m sorry, I can’t pay right now",
                    "I’m dealing with some personal issues",
                    "I’m waiting for financial help",
                    "I don’t have access to funds currently",
                    "I’m financially stressed",
                    "I’m unable to make the payment now"
                ],
            "reason to not pay": [
                    "I forgot to pay",
                    "I was not aware of the due date",
                    "I didn’t receive the payment reminder",
                    "I’m facing financial difficulties",
                    "I lost my job recently",
                    "I had some medical emergencies",
                    "I was out of town",
                    "I thought the payment was auto-deducted",
                    "I had technical issues while paying",
                    "The amount was higher than I expected",
                    "I had other urgent expenses",
                    "I was busy and forgot",
                    "I needed more time to arrange funds",
                    "I was confused about the policy status",
                    "I wasn’t informed properly",
                    "I had banking issues",
                    "I’m waiting for my salary",
                    "I had a dispute with the agent",
                    "I didn’t find the premium affordable",
                    "I’m planning to pay soon",
                    "I wanted to discuss options before paying"
                ],
        }
    },
    {
        "question": "I would like to inform you that the due date for renewal premium payment for your policy was on {premium_due_date}, the grace period for your policy is over due to non-payment of the regular premium and you are losing the benefit of your plan. Would you like to know what your policy's benefits you could get if you resume paying premiums?",
        "response": {
            "agree/DisAgree": [
                    "Yes, please tell me about the benefits",
                    "Yes, I want to know",
                    "Sure, please explain",
                    "Yes, I’m interested",
                    "Please tell me more",
                    "Yes, I would like to know",
                    "Yes, go ahead",
                    "Sure, tell me about the benefits",
                    "Yes, that would be helpful",
                    "I want to know the benefits",
                    "Yes, please continue",
                    "Yes, tell me what I get",
                    "I’m interested in the benefits",
                    "Yes, explain the benefits",
                    "Yes, please inform me",
                    "Yes, I want the details",
                    "Yes, please share",
                    "Yes, tell me everything",
                    "Yes, I’d like to hear about it"
                ],
        }
    },
    {
        "question": "Sir, you will get maximum Allocation in the Invested Fund i. e % of Premium which will boost up your investment. Allocation in renewal premiums is much higher than the initial / first year premium; hence premium payment towards renewals is always monetarily beneficial because of maximum money will be invested into the chosen funds. Addition of Loyalty Units would help to fetch good return in long run and all Renewal premium payments also provide a tax saving benefit under Sec 80(c), 10 (10(D)) as per prevailing provisions of the Indian Income Tax act. Does this help you make a more informed decision about your policy? ",
        "response": {
            "agree to pay":  [
                    "Yes, this helps me decide",
                    "Yes, I understand and will pay",
                    "Yes, I want to continue my policy",
                    "Yes, I will pay the renewal premium",
                    "This information is helpful, I will pay",
                    "Yes, I am convinced to continue",
                    "Yes, I want to invest further",
                    "Thanks, I will make the payment soon",
                    "Yes, I am clear now and will pay",
                    "Yes, I want to avail the benefits",
                    "Yes, I am ready to pay",
                    "Yes, this makes sense to me",
                    "Yes, I will renew my policy",
                    "Yes, I agree to pay",
                    "Yes, please proceed with the payment",
                    "Yes, I understand the benefits and will pay",
                    "Yes, this motivates me to continue",
                    "Yes, I will clear the dues soon",
                    "Yes, I want to get loyalty units",
                    "Yes, I am satisfied with the policy",
                    "Yes, I’m happy to continue",
                    "Yes, I will take advantage of the tax benefits",
                    "Yes, I’ll arrange the payment",
                    "Yes, this information helped me decide",
                    "Yes, I’m convinced, please continue",
                    "Yes, I’m interested in paying the premium"
                ],
            "already paid": [
                    "I have already paid the renewal premium",
                    "The payment has been made",
                    "I paid it recently",
                    "The renewal premium is already paid",
                    "I completed the payment yesterday",
                    "The outstanding amount has been cleared",
                    "Payment is done",
                    "I transferred the amount already",
                    "I have made the payment",
                    "It’s already paid",
                    "Payment was processed",
                    "I paid online",
                    "The bank transaction is complete",
                    "I have proof of payment",
                    "The payment was successful",
                    "I have cleared the dues",
                    "The renewal premium was paid on time",
                    "I already settled the premium",
                    "I took care of the payment",
                    "Payment confirmation received",
                    "The premium has been paid",
                    "I already cleared the balance"
                ],
            "don't have policy band": [
                    "I don’t have the policy bond",
                    "I don’t have the policy document",
                    "I lost the policy papers",
                    "I haven’t received the policy bond yet",
                    "I don’t know where the policy bond is",
                    "The policy document is missing",
                    "I can’t find the policy bond",
                    "I never got the policy papers",
                    "I don’t have any documents related to the policy",
                    "The policy bond was misplaced",
                    "I haven’t received any policy documents",
                    "I don’t have a copy of the policy",
                    "The policy bond was never given to me",
                    "I lost the original policy bond",
                    "I’m not aware of the policy bond",
                    "I have no paperwork for the policy",
                    "I didn’t get the policy bond in the mail",
                    "I don’t have any proof of the policy",
                    "I can’t produce the policy documents",
                    "I haven’t seen the policy bond"
                ],
            "can't pay": [
                    "I can’t pay right now",
                    "I’m unable to pay at the moment",
                    "I don’t have the money currently",
                    "I’m facing financial difficulties",
                    "I lost my job recently",
                    "I have other urgent expenses",
                    "I’m going through some tough times",
                    "I can’t arrange the funds right now",
                    "I’m waiting for my salary",
                    "I have some medical bills to pay",
                    "I’m not in a position to pay",
                    "I’m having financial problems",
                    "I can’t afford the premium now",
                    "I’m struggling to manage expenses",
                    "I need more time to pay",
                    "I’m sorry, I can’t pay right now",
                    "I’m dealing with some personal issues",
                    "I’m waiting for financial help",
                    "I don’t have access to funds currently",
                    "I’m financially stressed",
                    "I’m unable to make the payment now"
                ],
            "reason to not pay": [
                    "I forgot to pay",
                    "I was not aware of the due date",
                    "I didn’t receive the payment reminder",
                    "I’m facing financial difficulties",
                    "I lost my job recently",
                    "I had some medical emergencies",
                    "I was out of town",
                    "I thought the payment was auto-deducted",
                    "I had technical issues while paying",
                    "The amount was higher than I expected",
                    "I had other urgent expenses",
                    "I was busy and forgot",
                    "I needed more time to arrange funds",
                    "I was confused about the policy status",
                    "I wasn’t informed properly",
                    "I had banking issues",
                    "I’m waiting for my salary",
                    "I had a dispute with the agent",
                    "I didn’t find the premium affordable",
                    "I’m planning to pay soon",
                    "I wanted to discuss options before paying"
                ]
        }
    },
    {
        "question": "When would be a convenient time to call you again to provide the information about your policy with us? Please can you give a time and date?",
        "response": {
            "date/Time Provided":  [
                    "Tomorrow at 3 PM",
                    "Next Monday morning",
                    "Friday afternoon works for me",
                    "Anytime after 5 PM today",
                    "On 15th July at 10 AM",
                    "This Saturday around noon",
                    "Next week Tuesday at 2 PM",
                    "Tomorrow morning is good",
                    "Call me on Wednesday evening",
                    "I’m available on Friday at 4 PM",
                    "Please call me on 20th July at 11 AM",
                    "Monday at 9 AM works",
                    "Tuesday afternoon is fine",
                    "Can you call me next Thursday at 3 PM?",
                    "Call me after 6 PM today",
                    "I’ll be free on Saturday morning",
                    "Next Sunday at 10 AM",
                    "Please call on 25th July at 1 PM",
                    "Anytime tomorrow works",
                    "Call me on Monday after 2 PM",
                    "I’m available this Friday at 5 PM",
                    "How about Wednesday at 3 PM?",
                    "Please call after lunch tomorrow",
                    "Call me tomorrow evening",
                    "I’m free next Thursday morning",
                    "Call me next week Monday at 10 AM",
                    "Any day after 4 PM works for me",
                    "Please call on 18th July in the afternoon",
                    "Call me anytime after 3 PM tomorrow",
                    "I can talk on Friday afternoon"
                ]
        }
    },
    {
        "question": " Thank you sir/maam, I will arrange your call back at the given time.",
        "response": {
            "instantResponse": [
                    "Thank you.",
                    "Thanks.",
                    "Alright, thank you.",
                    "Okay, I’ll wait for the call.",
                    "Sure, I’ll be available then.",
                    "Thank you, looking forward to it.",
                    "Thanks for the update.",
                    "Okay, I appreciate it.",
                    "Thank you for arranging.",
                    "Thanks, I’ll keep my phone ready.",
                    "Alright, talk to you then.",
                    "Thank you, have a good day.",
                    "Thanks, I’ll be ready to take your call.",
                    "Okay, thank you for informing.",
                    "Thanks, I appreciate your help.",
                    "Thank you, I’ll be waiting.",
                    "Thanks, see you then.",
                    "Alright, thank you for the confirmation.",
                    "Thanks, I appreciate the follow-up.",
                    "Thank you, talk soon."
                ]
        }
    },
    {
        "question": "You can download the policy bond through whatsapp. Please send a message from your registered mobile number on 8806727272 and you will be able to download the policy bond. ",
        "response": {
            "instantResponse": [
                    "Thank you for the information.",
                    "Okay, I will send a message from my registered number.",
                    "Got it, I will try that.",
                    "Thanks, I will download it now.",
                    "Alright, I’ll message that number.",
                    "Thanks for the help.",
                    "Okay, I will do that right away.",
                    "Thank you, that’s helpful.",
                    "I will send the message shortly.",
                    "Thanks for guiding me.",
                    "I will check WhatsApp and send the message.",
                    "Thanks, I appreciate the info.",
                    "Okay, I’ll follow those instructions.",
                    "Thank you, I’ll try to download it now.",
                    "Got it, thanks!",
                    "Thanks for letting me know.",
                    "Okay, I’ll send the message from my registered mobile.",
                    "Thanks, that makes it easy.",
                    "I’ll do that now, thank you.",
                    "Thank you for the assistance."
                ]
        }
    },
    {
        "question": "May I know how you plan to make the payment? Will it be via cash, cheque, or online?",
        "response": {
            "cheque": [
                    "I will pay by cheque.",
                    "Cheque payment.",
                    "I prefer to pay via cheque.",
                    "I will issue a cheque.",
                    "Cheque is my payment method.",
                    "I’ll send a cheque.",
                    "Payment will be by cheque.",
                    "I plan to pay using cheque.",
                    "I’ll pay with a cheque.",
                    "Cheque will be used for payment.",
                    "I’m going with cheque payment.",
                    "Cheque payment option for me.",
                    "I’ll write a cheque for the premium.",
                    "I prefer cheque over cash or online.",
                    "Cheque is how I’ll pay.",
                    "I’ll drop a cheque at the office.",
                    "I’ll mail the cheque.",
                    "I’ll do cheque payment.",
                    "Cheque is the method I choose.",
                    "I intend to pay by cheque."
                ],
            "branch":  [
                    "Which branch should I visit?",
                    "Where is the nearest branch?",
                    "Can you tell me the branch address?",
                    "I want to visit the branch.",
                    "Please provide branch contact details.",
                    "Is there a branch near me?",
                    "Which branch handles my policy?",
                    "I prefer to talk at the branch.",
                    "Can I submit documents at the branch?",
                    "Do you have a branch in my city?",
                    "I will visit the branch tomorrow.",
                    "Please tell me the branch timings.",
                    "Is the branch open today?",
                    "Which branch should I go to for payment?",
                    "I want to meet someone at the branch.",
                    "Can I get the branch phone number?",
                    "Is branch service available on weekends?",
                    "I need assistance at the branch.",
                    "I will drop by the branch.",
                    "Please confirm the branch location."
                ],
            "Gives Data": [
                    "Here is the policy number: 123456789.",
                    "My date of birth is 15th August 1980.",
                    "The premium amount paid is ₹10,000.",
                    "My registered mobile number is 9876543210.",
                    "The policy started on 1st January 2020.",
                    "I have paid premiums up to June 2024.",
                    "The outstanding amount is ₹5,000.",
                    "My address is 123 Main Street, Mumbai.",
                    "The nominee name is John Doe.",
                    "My email ID is example@mail.com.",
                    "The last payment date was 20th March 2025.",
                    "The policy status is active.",
                    "My client ID is ABCD1234.",
                    "The policy type is term insurance.",
                    "The payment mode was online transfer.",
                    "The loan against policy is ₹50,000.",
                    "I have received the policy documents.",
                    "The claim amount settled was ₹1,00,000.",
                    "My bank account number ends with 7890.",
                    "The agent’s name is Mr. Sharma."
                ],
            "customer confirms payment details": [
                    "Yes, the payment details are correct.",
                    "That’s the correct amount I paid.",
                    "Yes, I confirm the payment.",
                    "The payment information matches my records.",
                    "Yes, I made the payment on that date.",
                    "That is the payment I made.",
                    "I confirm the payment amount and date.",
                    "Yes, the transaction details are accurate.",
                    "I acknowledge the payment.",
                    "The payment details are as you mentioned.",
                    "Yes, I can confirm the payment.",
                    "The payment was made as stated.",
                    "Yes, that’s the payment I completed.",
                    "I confirm the premium payment details.",
                    "Yes, the payment has been made accordingly.",
                    "That’s the correct payment information.",
                    "I verify the payment details.",
                    "Yes, I made the payment for that policy.",
                    "I confirm the payment amount and status.",
                    "The payment details provided are accurate."
                ]
        }
    },
    {
        "question": "If you wish, you can pay online now. We’ll send you a link, or you can visit our website. You can use Debit card, Credit card, Net banking, PhonePe, Whatsapp or Google Pay to make the payment.",
        "response": {
            "branch":  [
                    "Can I pay at the branch instead?",
                    "Is it possible to pay in cash at the branch?",
                    "I prefer to visit the branch for payment.",
                    "Do you accept cheque payments at the branch?",
                    "Can I come to the branch to make the payment?",
                    "I want to pay the premium at the nearest branch.",
                    "Is the branch open for payments now?",
                    "Please tell me the branch address for payment.",
                    "I would rather pay at the branch than online.",
                    "Can I pay by cash or cheque at your branch?",
                    "I don’t want to pay online, I will visit the branch.",
                    "Is there a branch near me where I can pay?",
                    "Can I get a receipt if I pay at the branch?",
                    "I will come to the branch tomorrow to pay.",
                    "Do you provide assistance at the branch for payment?",
                    "I’m not comfortable paying online, I prefer branch payment.",
                    "Can I speak to someone at the branch about payment?",
                    "I will visit the branch to complete the payment.",
                    "Is branch payment accepted for renewal premiums?",
                    "I want to pay directly at the branch office."
                ],
        }
    },
    {
        "question": " You can conveniently pay the premium from home without visiting the branch. I’m here to assist you with the digital payment process. ",
        "response": {
            "Gives Data": [
                    "My registered mobile number is 9876543210.",
                    "Please send the payment link to my email: example@mail.com.",
                    "My policy number is 123456789.",
                    "You can send the payment link to my WhatsApp number.",
                    "My email ID is john.doe@example.com.",
                    "Please share the payment link on my registered phone.",
                    "My bank account number ends with 4567.",
                    "Send the payment link to my mobile number registered with you.",
                    "I will need the link on my WhatsApp.",
                    "My policy ID is ABCD1234.",
                    "Please email me the payment instructions.",
                    "I prefer to receive the link via SMS.",
                    "My phone number is 9988776655, please send the link there.",
                    "Send the payment details to my email.",
                    "My registered email is john@example.com.",
                    "Please share the link on my mobile number.",
                    "I will pay using the link sent to my WhatsApp.",
                    "My customer ID is 789012.",
                    "Please provide the payment link on my registered contact.",
                    "You can send the payment details to my phone."
                ]
        }
    },
    {
        "question": "I’m noting your preference. I’ll send you a payment link for easy processing.",
        "response": {
            "customer confirms payment details": [
                    "Thank you, I’ll check the link.",
                    "Okay, I’ll look out for the payment link.",
                    "Got it, I’ll use the link to pay.",
                    "Thanks, I’ll confirm once the payment is done.",
                    "Alright, I’ll complete the payment using the link.",
                    "Thank you for sending the link.",
                    "I’ll follow up after making the payment.",
                    "Okay, I’ll process the payment shortly.",
                    "Thanks, I confirm I’ll pay via the link.",
                    "I will make sure to use the link you send.",
                    "Thank you, I acknowledge the payment method.",
                    "I’ve noted that and will pay using the link.",
                    "Thanks, I’ll confirm once I’ve paid.",
                    "Okay, I’ll use the link for payment.",
                    "Thank you, I’m ready to pay online.",
                    "I appreciate it, I’ll check my messages.",
                    "Thanks, I’ll complete the payment soon.",
                    "Got it, I’m waiting for the link.",
                    "Thanks, I’ll make the payment as instructed.",
                    "Okay, I confirm the payment process."
                ]
        }
    },
    {
        "question": "As confirmed, you’ll pay the premium on October 5, 2024, at 10:00 AM via online transfer. Please ensure timely payment to maintain your policy benefits. We’ll call to confirm the payment status.",
        "response": {
            "instantResponse": [
                    "Yes, I confirm the payment schedule.",
                    "Okay, I will make the payment on October 5 at 10 AM.",
                    "Thank you, I’ll ensure the payment is done on time.",
                    "I acknowledge the payment date and method.",
                    "Confirmed, I’ll pay via online transfer as scheduled.",
                    "I’ll complete the payment on October 5 at 10 AM.",
                    "Yes, I will be ready to make the payment then.",
                    "Thanks for the confirmation, I’ll pay accordingly.",
                    "I’ve noted the date and will pay online.",
                    "Okay, I will follow through with the payment on time.",
                    "I confirm the payment plan as discussed.",
                    "I’ll make sure the payment is processed on that day.",
                    "Thanks, I’ll be ready to pay on October 5.",
                    "Confirmed, I’ll pay online on the scheduled date.",
                    "I appreciate the reminder and will pay as agreed.",
                    "Yes, I’ll ensure timely payment.",
                    "I’ll be making the payment via online transfer as stated.",
                    "Thanks for the update, I’ll comply with the schedule.",
                    "Payment scheduled for October 5 at 10 AM, noted.",
                    "Understood, I’ll pay at the scheduled time."
                ]
        }
    },
    {
        "question": "Thank you for making the payment. May I know when you made the payment? ",
        "response": {
            "last week or provide any date": [
                    "I made the payment last week.",
                    "The payment was done last Monday.",
                    "I paid it on 3rd July.",
                    "The payment was completed last Friday.",
                    "I made the payment on July 5th.",
                    "It was paid last Wednesday.",
                    "I completed the payment on 1st July.",
                    "Payment was made last Tuesday.",
                    "I paid on the 10th of July.",
                    "The payment was done last Thursday.",
                    "I made the payment last weekend.",
                    "I paid it on 15th June.",
                    "Payment was completed on June 28th.",
                    "I made the payment on the 20th of July.",
                    "It was paid last Saturday.",
                    "The payment was done on July 7th.",
                    "I paid last Wednesday evening.",
                    "Payment was made on July 2nd.",
                    "I completed the payment last Monday morning.",
                    "I made the payment on June 30th.",
                    "I paid the premium last week Thursday.",
                    "Payment was done last Friday afternoon.",
                    "I paid on 25th June.",
                    "It was completed last Tuesday morning.",
                    "Payment was done last Sunday.",
                    "I made the payment on July 1st.",
                    "I paid last Monday afternoon.",
                    "Payment was done on the 4th of July.",
                    "I completed the payment last Thursday.",
                    "It was paid last week Friday."
                ],
            "anything else":  [
                    "No, that’s all for now.",
                    "No, thank you.",
                    "Nothing else at the moment.",
                    "No, I’m good, thanks.",
                    "That’s everything, thanks.",
                    "No further questions.",
                    "No, I don’t need anything else.",
                    "Nothing else I can think of.",
                    "No, I’m satisfied for now.",
                    "No, that’s all I needed.",
                    "No, thanks for your help.",
                    "No, that covers it.",
                    "Nothing else right now.",
                    "No, I’m all set.",
                    "No, thank you for your assistance.",
                    "No, that’s all from my side.",
                    "No, I have no more queries.",
                    "No, I’m fine for now.",
                    "No, I don’t need anything more.",
                    "No, that’s everything."
                ]
        }
    },
    {
        "question": "May I know where you made the payment (e.g., online, cheque, or cash)?",
        "response": {
            "online/case/cheque": [
                    "I made the payment online.",
                    "Payment was done through net banking.",
                    "I paid using my debit card online.",
                    "I used credit card for the payment.",
                    "The payment was via online transfer.",
                    "I paid through PhonePe.",
                    "Payment was done using Google Pay.",
                    "I completed the payment on your website.",
                    "I paid via UPI online.",
                    "Payment was done through an online app.",
                    "I transferred the amount online.",
                    "I used online banking to pay.",
                    "The payment was made through WhatsApp link.",
                    "I paid using a mobile payment app.",
                    "I completed the payment online yesterday.",
                    "I paid in cash at the branch.",
                    "Payment was made by cash.",
                    "I visited the office and paid cash.",
                    "I paid the premium in cash.",
                    "Cash payment was done at your office.",
                    "I made a cash payment yesterday.",
                    "I paid the amount in cash directly.",
                    "The payment was done by cash.",
                    "I handed over cash to the agent.",
                    "I deposited cash at the branch.",
                    "Payment was made in cash on the due date.",
                    "I paid cash at the collection center.",
                    "I paid by cash at your branch.",
                    "Cash was given for the premium payment.",
                    "I made the payment by cheque.",
                    "Payment was done through cheque.",
                    "I issued a cheque for the premium.",
                    "I paid via cheque.",
                    "Cheque payment was made at the branch.",
                    "I sent the cheque by post.",
                    "I handed over a cheque to the agent.",
                    "Payment was made using a cheque.",
                    "I mailed the cheque for payment.",
                    "I gave a cheque for the premium.",
                    "The payment was through cheque transaction.",
                    "I wrote a cheque to pay the premium.",
                    "Cheque was deposited at the branch.",
                    "I used cheque as the payment method."
                ],
            "anything else": [
                    "No, that's all. Thank you.",
                    "Nothing else, thanks.",
                    "No, I’m good for now.",
                    "That’s it from my side.",
                    "No, I don’t need anything else.",
                    "No further questions, thank you.",
                    "I’m all set, thanks.",
                    "That will be all.",
                    "No, everything is clear.",
                    "No, I’m fine now.",
                    "Nope, I’m good.",
                    "That’s everything, thank you.",
                    "No, thanks for your help.",
                    "No, I’m okay for now.",
                    "No, you've answered everything.",
                    "Yes, I have one more question.",
                    "Actually, can you also help me with something else?",
                    "Yes, I need clarification on another point.",
                    "I do have another query.",
                    "Can you also guide me on the benefits?",
                    "Yes, I want to know about the grace period.",
                    "One more thing, please.",
                    "Can you tell me how to update my contact details?",
                    "Yes, I’d like to know the surrender value too.",
                    "Actually, I’d like to change my nominee details.",
                    "Yes, when will I receive the receipt?",
                    "Can I get the agent’s contact details too?"
                ]
        }
    },
    {
        "question": "Could you please provide the transaction id or reference id? For cheque payments, we’ll need the cheque number. I can assist with further tracking if needed.",
        "response": {
            "instantResponse": [
                    "Yes, the transaction ID is TXN123456789.",
                    "Sure, the reference number is REF908172634.",
                    "The UPI reference ID is 1234ABCD5678.",
                    "The cheque number is 445678.",
                    "Here is the transaction ID: 87654321.",
                    "I paid via GPay, and the UPI ID is GPAY123456.",
                    "The cheque I issued is number 123456.",
                    "Yes, the reference code is XYZ789654.",
                    "Cheque number is 987654.",
                    "I’ve shared the transaction details via WhatsApp.",
                    "The bank reference ID is 789456123.",
                    "It was a PhonePe transaction with ID PH1234567.",
                    "Here’s the NEFT ID: NEFT123456789.",
                    "Yes, the transaction number is available. It’s 45678910.",
                    "I made the payment via net banking. Ref: NB12345678.",
                    "I’ll check and share the transaction ID shortly.",
                    "I don’t have it right now, will send it soon.",
                    "I’ll get the cheque number and send it later.",
                    "Let me retrieve it and share with you in a bit.",
                    "I'll message you the transaction ID once I find it.",
                    "I’ll send the details after checking my bank statement.",
                    "Please give me some time to fetch it.",
                    "I’ll forward the transaction details by evening.",
                    "I'll share it via SMS or WhatsApp shortly.",
                    "Let me check my messages and get back to you.",
                    "I’ll need to confirm it from my bank, will update you.",
                    "I don’t have the transaction ID right now.",
                    "I lost the payment message.",
                    "I didn’t save the reference number.",
                    "I can’t find the cheque number.",
                    "I don’t remember the transaction ID.",
                    "I paid in cash, so there’s no transaction ID.",
                    "I no longer have the receipt.",
                    "It was done by someone else; I don’t have the details.",
                    "Sorry, I don’t have that information.",
                    "I misplaced the cheque counterfoil.",
                    "I didn't receive any reference number."
                ]
        }
    },
    {
        "question": "I understand your concern. To achieve your financial goals, staying invested is key. You can pay via credit card, EMI, or change your payment mode to monthly. Can you arrange the premium to continue benefits?",
        "response": {
            "instantResponse":  [
                "Yes, I will arrange the premium.",
                "Okay, I’ll continue the policy.",
                "Thanks, I’ll pay it today.",
                "Yes, I’ll make the payment shortly.",
                "I will pay via credit card.",
                "Sure, I want to continue the benefits.",
                "Okay, I will manage it through EMI.",
                "Yes, I’ll try to pay it by this week.",
                "I understand. I’ll arrange the premium.",
                "I’ll pay now to keep the policy active.",
                "Can you please convert it to monthly?",
                "EMI sounds good — how do I proceed?",
                "Is it possible to shift to monthly mode?",
                "I prefer to pay in installments, please guide me.",
                "Can you help me switch the payment mode?",
                "Yes, but I want to convert it to EMI.",
                "Monthly option would be more manageable for me.",
                "Please help me set up a credit card EMI.",
                "I’ll continue if it’s on EMI.",
                "Yes, but I want to change the payment frequency first.",
                "I can’t pay at the moment.",
                "Sorry, I won’t be able to continue.",
                "I’m still not in a financial position to pay.",
                "I’ve already decided to discontinue.",
                "Even with EMI, it’s difficult for me.",
                "No, I’m unable to arrange the amount.",
                "I’m not interested in continuing the policy.",
                "I can’t afford the premium right now.",
                "I’ll think about it but can’t commit now.",
                "It’s not possible at the moment, sorry.",
                "How does EMI work for insurance premium?",
                "What’s the process to switch to monthly payments?",
                "Will I get the same benefits with EMI?",
                "What happens if I delay by a few days?",
                "Can I pay partially now and the rest later?",
                "Is there any charge for converting to EMI?",
                "Will I lose benefits if I don’t pay this month?",
                "Can someone call me to explain EMI options?",
                "Can I pay with two different methods?",
                "Is auto-debit possible for monthly payments?"
            ]
        }
    },
    {
        "question": "You can opt for the Partial Withdrawal option after completing 5 years of the policy i.e ,lock-in period. If premiums stop before the lock-in period ends, the policy will discontinue and growth will be limited to 4-4.5% returns. Also you will lose your sum assured value of {sum_assured}. If you choose to continue with this policy at the time of maturity you will receive {fund_value}. Would you be willing to pay your premium now?",
        "response": {
            "yes":  [
                    "Yes, I will pay the premium.",
                    "Okay, I’ll make the payment now.",
                    "Yes, I want to continue the policy.",
                    "Sure, I will pay to avoid losing the benefits.",
                    "Yes, I understand. I’ll make the payment.",
                    "I don’t want to lose the sum assured, I will pay.",
                    "Yes, I will proceed with the payment.",
                    "Alright, I’ll pay now to keep it active.",
                    "Yes, I want the maturity benefits, so I’ll pay.",
                    "Yes, continuing the policy makes sense. I’ll pay.",
                    "Okay, I’ll arrange the premium today.",
                    "Yes, I’m ready to make the payment.",
                    "Thank you for explaining, I will pay now.",
                    "I want to receive the fund value, so I’ll continue.",
                    "Yes, I don’t want to discontinue the policy.",
                    "Sure, I’ll make the payment to avoid loss.",
                    "Yes, let me complete the payment process.",
                    "I’m convinced, I’ll pay now.",
                    "Yes, I want to keep the policy active.",
                    "Okay, I’ll arrange the funds and pay today."
                ],
            "no": [
                    "No, I can’t pay right now.",
                    "I’m not in a position to make the payment.",
                    "No, I won’t be continuing the policy.",
                    "Sorry, I can’t manage the premium at this time.",
                    "No, I’ve decided not to continue.",
                    "I’m not able to pay at the moment.",
                    "No, I don’t wish to invest further.",
                    "I understand, but I can’t pay now.",
                    "No, the amount is too high for me currently.",
                    "I’ll have to skip this payment.",
                    "No, I can’t afford to continue the policy.",
                    "I’m not interested in paying the premium.",
                    "No, please consider the policy closed.",
                    "I don’t have funds available for the premium.",
                    "No, I’ll discontinue the policy for now.",
                    "I’ve other priorities, so I won’t be paying.",
                    "I don’t want to proceed with the policy anymore.",
                    "No, I don’t see value in continuing this plan.",
                    "I’m not in a financial condition to pay.",
                    "No, I’ve already decided not to renew."
                ]
        }
    },
]